routes/web.php
<?php

Auth::routes();

Route::get('/', function() {
    return redirect()->to('/candidat');
});

Route::group([ 'prefix' => 'dashboard','middleware' =>['auth']],function(){

  Route::get('/','DashboardController@index');
  Route::resource('tests', 'TestsController');
  Route::group(['prefix' => 'tests/{test}'], function() {
    Route::resource('quiz', 'QuizesController');
  });


  Route::group(['prefix' => 'users/{id}/tests'], function() {
      Route::get('/','UsersController@tests')->name('users.tests');
      Route::get('/{test_id}','UsersController@test')->name('users.tests.show');
      Route::post('/{test_id}','UsersController@updateTest')->name('users.tests.update');
      Route::put('/{test_id}','UsersController@resetTest')->name('users.tests.reset');
      Route::get('/{test_id}/report','UsersController@report')->name('users.tests.report');
  });
  Route::resource('users','UsersController');

  Route::group(['prefix' => 'media'], function() {
    Route::get('/','MediaController@index')->name('media.index');
    Route::post('/','MediaController@store')->name('media.store');
    Route::delete('/{id}','MediaController@destroy')->name('media.destroy');
  });


});


Route::group(['prefix' => 'candidat'], function()
{
  Route::get('login','CandidatController@login')->name('candidat.login');
  Route::post('login','CandidatController@handleLogin')->name('candidat.login');
  Route::group(['middleware' => ['auth']], function() {
    Route::get('tests','CandidatController@tests');
    Route::get('/','CandidatController@tests')->name('candidat.tests');

    Route::get('test/{id}/end','CandidatController@test_end')->name('candidat.test_end');
    Route::get('test/{id}','CandidatController@test')->name('candidat.test')->middleware('tavailable');
    Route::post('test/{id}','CandidatController@postTest');
  });

});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Test;

class DashboardController extends Controller
{
    public function index()
    {
        $tests = Test::count();
        $users = User::count() - 1;
        return view('dashboard.home',compact('tests','users'));
    }
}

resources/views/dashboard/partials/flash.blade.php
@if (Session::has('errors'))
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <ul class="list-unstyled">
        @foreach (Session::get('errors')->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
        </ul>
    </div>
@endif


@if (Session::has('warning'))
    <div class="alert alert-warning" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        {{Session::get('warning')}}
    </div>
@endif


@if (Session::has('info'))
    <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        {{Session::get('info')}}
    </div>
@endif


@if (Session::has('success'))
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        {{Session::get('success')}}
    </div>
@endif

resources/views/dashboard/partials/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-inner">
        <!-- ### $Sidebar Header ### -->
        <div class="sidebar-logo">
            <div class="peers ai-c fxw-nw">
                <div class="peer peer-greed">
                    <a class='sidebar-link td-n' href="/dashboard" class="td-n">
                        <div class="peers ai-c fxw-nw">
                            <div class="peer">
                                <div class="logo">
                                    <img src="/images/gva_logo_small.png" style="width: 70%; height: auto; padding: 10px" alt="">
                                </div>
                            </div>
                            <div class="peer peer-greed">
                                <h5 class="lh-1 mB-0 logo-text">GVA</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="peer">
                    <div class="mobile-toggle sidebar-toggle">
                        <a href="" class="td-n">
                            <i class="ti-arrow-circle-left"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!-- ### $Sidebar Menu ### -->
        <ul class="sidebar-menu scrollable pos-r">
            <li class="nav-item mT-15 active">
                <a class='sidebar-link' href="/dashboard" default>
					<span class="icon-holder">
						<i class="c-blue-500 ti-home"></i>
					</span>
                    <span class="title">Dashboard</span>
                </a>
            </li>
            <li class="nav-item mT-15 ">
                <a class='sidebar-link' href="{{ route('tests.index') }}" default>
					<span class="icon-holder">
						<i class="c-red-500 ti-file"></i>
					</span>
                    <span class="title">Tests</span>
                </a>

            </li>
            <li class="nav-item mT-15 ">
                <a class='sidebar-link' href="{{ route('users.index') }}" default>
					<span class="icon-holder">
						<i class="c-green-500 ti-user"></i>
					</span>
                    <span class="title">Candidats</span>
                </a>
            </li>

            <li class="nav-item mT-15 ">
                <a class='sidebar-link' href="{{ route('media.index') }}" default>
                    <span class="icon-holder">
                        <i class="c-blue-500 ti-volume"></i>
                    </span>
                    <span class="title">Media</span>
                </a>
            </li>

        </ul>
    </div>
</div>

resources/views/dashboard/partials/spinner.blade.php
<!-- @Page Loader -->
<!-- =================================================== -->
<div id='loader'>
    <div class="spinner"></div>
</div>

<script type="text/javascript">
  window.addEventListener('load', () => {
    const loader = document.getElementById('loader');
    setTimeout(() => {
      loader.classList.add('fadeOut');
    }, 300);
  });
</script>

resources/views/dashboard/partials/topbar.blade.php
<div class="header navbar">
    <div class="header-container">
        <ul class="nav-left">
            <li>
                <a id='sidebar-toggle' class="sidebar-toggle" href="javascript:void(0);">
                    <i class="ti-menu"></i>
                </a>
            </li>

        </ul>
        <ul class="nav-right">


            <li class="dropdown">
                <a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
                    <div class="peer mR-10">
                        <div><i class="fa fa-user"></i></div>
                    </div>
                    <div class="peer">
                        <span class="fsz-sm c-grey-900">{{ auth()->user()->name }}</span>
                    </div>
                </a>
                <ul class="dropdown-menu fsz-sm">
                    <li>
                        <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                            <i class="ti-user mR-10"></i>
                            <span>Profile</span>
                        </a>

                    </li>
                    <li>
                        <form action="/logout" method="POST">
                            {{ csrf_field() }}
                            <button class="menu-btn d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                                <i class="ti-power-off mR-10"></i>
                                <span>Logout</span>
                            </button>
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>